### ISSUE TITLE
windows terminal unexpected behaviour

### ISSUE THREAD

**Issue by matas-noreika** [matas-noreika/terminal_Snake#9]
Hi @markdeegan,

I tested my program on both POSIX and windows and encounter only an issue while using the standard terminal for windows. The POSIX and msys terminals ran the program without yielding until a input was passed into the stdin buffer. The windows terminal essentially didnt move the snake automatically and instead waited for user to press a key. I tried turining of quick edit mode manual and through the program but saw no effect. If you have any solution or better understanding of whats happening that would be helpful thank you.

**Comment by markdeegan** [comment]
I don't have a great understanding of what is going on here, but as you are using ASCII special characters for input on the POSIX sytstem, you might want to lool at something more part of the c language (and Windows implementation) like getchar or something. Not an ideal solution I know, and it moves away from the low-level; ASCII stuff you are using on POSIX, but it may provide a temporary fix.

**Comment by matas-noreika** [comment]
@markdeegan,
I managed to get the windows terminal to work like on the POSIX system. The issue seems to be in the reading of the stdin buffer I believe its the way I try to read the number of keypresses in the buffer. I will try see if ASCII characters have an effect thank you

**Comment by matas-noreika** [comment]
I found a solution to the bug its a result of two annoying properties of the windows console api.
first the ReadConsole() and readConsoleInput() yield until at least 1 event is passed into the buffer. 
Second the windows console api does not provide a function other that peekConsoleInput() to read from buffer without affecting it. 
The solution is to use both peekConsoleInput() to read the buffer and loop through to find if a key was pressed. If the key is not found the function returns and stops the rest of the readTerminalInput() function.
If a key was found the read will continue as before except this time will remove each entry from the stdin buffer.
Using this solution the windows terminal executes each frame without yielding and performs exactly like on a POSIX shell.
